version: "3"

services:
  
  rust-network:
    image: simplestakingcom/tezedge-debugger:v0.1.0
    build: .
    ports:
      # Node specific ports
      - "10300:4927"       # node WS port (required only for tezedge)
      - "10200:9732"       # node P2P port
      - "10100:18732"      # node RPC port
      # Debugger Ports must be specified on node service, because of debugger network_mode attaches
      # debugger's container to the node container, allowing it to analyze node's traffic
      - "10000:13031"      # debugger RPC port
      - "10001:13131/udp"  # debugger syslog port
    entrypoint: sleep inf

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    command:
      - "--global_housekeeping_interval=1m"
      - "--housekeeping_interval=1m"
      - "--max_housekeeping_interval=1m"
      - "--application_metrics_count_limit=1"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  rust-debugger:
    image: simplestakingcom/tezedge-debugger:v0.1.0
    build: .
    network_mode: "service:rust-network"
    environment:
      - RUST_BACKTRACE=1
      - SLACK_HOOKS_URL=https://hooks.slack.com/services/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
      - CADVISOR_URL=http://cadvisor:8080
    volumes:
      - "rust-shared-data:/tmp/volume"
    entrypoint: ./tezedge-debugger
    depends_on:
      - cadvisor

  rust-node:
    image: simplestakingcom/tezedge:v0.2.0
    entrypoint: sh -c "sleep 5 && /home/appuser/tezedge/docker/compose/tezedge.sh"
    network_mode: "service:rust-network"
    depends_on:
      - rust-debugger
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "rust-shared-data:/tmp/tezedge"

volumes:
  rust-shared-data:
    external: false
